# Generated by Django 5.2.5 on 2025-08-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema', models.CharField(choices=[('fantasia', 'Fantasia'), ('ciencia_ficcion', 'Ciencia Ficción'), ('moderno', 'Moderno')], max_length=20)),
                ('descripcion', models.TextField()),
                ('es_publico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema_conversacion', models.CharField(blank=True, max_length=200)),
                ('capacidad_maxima', models.IntegerField(default=50)),
                ('fondo', models.ImageField(upload_to='salas/')),
                ('mundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='world.mundo')),
            ],
            options={
                'unique_together': {('mundo', 'nombre')},
            },
        ),
    ]
