# Generated by Django 5.2.5 on 2025-08-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_en_juego', models.CharField(help_text='Tu nombre público en SociaQuest', max_length=50, unique=True)),
                ('nivel', models.IntegerField(default=1, help_text='Nivel de experiencia social')),
                ('xp', models.IntegerField(default=0, help_text='Puntos de experiencia acumulados')),
                ('carisma', models.IntegerField(default=1, help_text='Habilidad para socializar')),
                ('empatia', models.IntegerField(default=1, help_text='Habilidad para entender a otros')),
                ('estilo_avatar', models.CharField(choices=[('aventurero', 'Aventurero'), ('elegante', 'Elegante'), ('geek', 'Geek'), ('deportista', 'Deportista')], default='aventurero', max_length=20)),
                ('color_principal', models.CharField(default='#4A90E2', max_length=7)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('sala_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.sala')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
                'ordering': ['-nivel', 'nombre_en_juego'],
            },
        ),
    ]
